### ISSUE TITLE
Support coffeescript 2

### ISSUE THREAD

**Issue by zvin** [balena-io-modules/node-balena-lint#18]
I'm getting `Undefined identifier "await".` errors.

**Comment by pimterry** [comment]
@zvin where are we using coffeescript 2? I don't think we should be at all - I thought anything getting upgraded should be upgrading to TS instead.

**Comment by zvin** [comment]
@pimterry 
I see no reason not to update to coffeescript2. It requires no code changes and does not prevent us from moving to typescript.
It can even help moving to typescript as cs2 outputs ES6 javascript.
The image-maker has been updated to cs2 for example.

**Comment by pimterry** [comment]
Ok. One of the reasons is things like this issue: it's not easy (afaict) to make resin-lint support both coffeescript 1 & coffeescript 2 at the same time, because we'd need to install coffeelint at both version 1 & 2, and differentiate between them somehow. We're trying to remove coffeescript everywhere, so it's not super worthwhile to fix this, and imo we shouldn't (though that's debatable).

We should watch out a little with CS2 updates anyway btw, there definitely are a few subtle breaking changes in CS2 that require code changes: http://coffeescript.org/#breaking-changes

Converting to TypeScript isn't that hard, and we should be planning to do it in the image maker as soon as we can anyway - it's been really really useful everywhere else. If you've got ES6 output (either via CS2 or we've been using https://github.com/decaffeinate/decaffeinate on CS1 projects) then you're pretty close to TS already, you just need to tidy up the few messy things that CS can leave behind, and go through and add types until the compiler is happy. Ping in FD if you want help with that, there's quite a few people now who've got a lot of practice of this, and we can definitely get it sorted!

In fact, it looks like the image maker is already 3% TS, I think @Page- has been quietly adding it: https://github.com/resin-io/resin-image-maker/blob/master/src/storage/passthrough.ts

**Comment by thgreasi** [comment]
v6 just dropped support for coffeescript, so I guess we can close this.
